name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - 'BF-*'
      - 'PU-*'
      - 'DOC-*'
      - 'hotfix-*'
      - 'fix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - 'main'
      - 'release-*'
      - 'DOC-*'
      - 'hotfix-*'

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  ruby-macOS:
    name: ruby-macOS
    needs:
      - version
    secrets: inherit
    uses: ./.github/workflows/ruby-macOS.yml

  deploy-tag:
    needs:
      - version
      - ruby-macOS
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.cc_changes }}